# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ruan Chaves
email: ruanchaves93@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Computational Linguistics, Natural Language Processing, Deep Learning.
twitter_username: ruanchaves93
github_username: ruanchaves
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ruan Chaves"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "Computational Linguistics, Deep Learning, Natural Language Processing."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ruanchaves.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ruanchaves93"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ruanchaves"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruanchaves/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ruanchaves93"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ruanchaves"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruanchaves/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-63563501-2"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "ruanchaves"

google_site_verification: "RrQzRh3eDne-H2Ub4vhAakQ6fcMi01lWSh2uVzZu0-8"

twitter:
  username: "ruanchaves"

social:
  links:
    - "https://twitter.com/ruanchaves93"
    - "https://www.linkedin.com/in/ruanchaves"
